version: 2
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  build:
    docker:
      - image: circleci/node:16.13

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

      - aws-cli/setup:
          aws-access-key-id: AKIAX5MELV7ZQ737OHAR 
          aws-secret-access-key: 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 
          aws-region: eu-west-2 

      - run:
          name: Deploy application
          command: sls deploy
